Fix compilation with newer Xorg versions
Xorg 1.18 stopped exporting some xfont related symbols in its
headers/shared libraries, which causes QXL to fail to build:

uxa-damage.c:947:5: error: implicit declaration of function 'QueryGlyphExtents' [-Werror=implicit-function-declaration]
     QueryGlyphExtents(font, charinfo, n, &extents);

The missing definition can be found in xfont, so this commit addes the
needed configure.ac checks and includes.
Note that dixfontstr.h must be included before the xfont headers or this
will cause compile-time warnings on older Xorg versions (eg 1.17)